// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizWebsite.Infrastructure.Data;

namespace QuizWebsite.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuizWebsite.Core.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d7bd26f-0df3-4fae-9c9b-cd9e80620cca"),
                            AnswerText = "Russia",
                            ExtraInfo = "17,098,242 Km²",
                            Points = 1,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("3831695c-cbfe-4d68-8a2a-e512dfcb4618"),
                            AnswerText = "Canada",
                            ExtraInfo = "9,984,670 Km²",
                            Points = 2,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("fe7698c7-1c14-4095-adf1-bfcb3eb21ced"),
                            AnswerText = "USA",
                            ExtraInfo = "9,833,517 Km²",
                            Points = 3,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("3b2fd177-28f0-4883-bc24-b3b93bdd7e6b"),
                            AnswerText = "The United States",
                            ExtraInfo = "9,833,517 Km²",
                            Points = 3,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("3c12adf3-8a34-4699-bb63-50738ec4b048"),
                            AnswerText = "United States",
                            ExtraInfo = "9,833,517 Km²",
                            Points = 3,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("065ef342-cc8a-49de-9527-a1f0674b26d0"),
                            AnswerText = "China",
                            ExtraInfo = "9,596,960 Km²",
                            Points = 4,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("ba7b5c71-1963-4ee9-8b9b-03d3576c4ab2"),
                            AnswerText = "Brazil",
                            ExtraInfo = "8,515,770 Km²",
                            Points = 5,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c5732964-aad7-40d9-a017-fde583a5cd1f"),
                            AnswerText = "Australia",
                            ExtraInfo = "7,741,220 Km²",
                            Points = 6,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("6a4bf586-b178-4658-a49f-c3f32a00c27e"),
                            AnswerText = "India",
                            ExtraInfo = "3,287,263 Km²",
                            Points = 7,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("89281623-75d7-4648-8120-fe425337fc64"),
                            AnswerText = "Argentina",
                            ExtraInfo = "2,780,400 Km²",
                            Points = 8,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("aa528fb6-860c-4157-be50-a2f8b1b2d522"),
                            AnswerText = "Kazakhstan",
                            ExtraInfo = "2,724,900 Km²",
                            Points = 9,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("76811c12-224c-4f2e-9752-a4c9914aada6"),
                            AnswerText = "Algeria",
                            ExtraInfo = "2,381,740 Km²",
                            Points = 10,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("427131c5-27b8-4a08-a173-fa2870c78e43"),
                            AnswerText = "China",
                            ExtraInfo = "1,439,323,776",
                            Points = 1,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b91d95dd-8c75-4394-8ce0-4aab8a073896"),
                            AnswerText = "India",
                            ExtraInfo = "1,380,004,385",
                            Points = 2,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("88fd8d65-6828-4638-8640-c59ecd65aaec"),
                            AnswerText = "USA",
                            ExtraInfo = "331,002,651",
                            Points = 3,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3f96744-6217-4754-813b-489e2f99131e"),
                            AnswerText = "The United States",
                            ExtraInfo = "331,002,651",
                            Points = 3,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("4d99a88a-64f1-4f85-9bb2-f0c6b8b34238"),
                            AnswerText = "United States",
                            ExtraInfo = "331,002,651",
                            Points = 3,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("3f0f4dc9-3d0e-4af8-8872-2aa221f82196"),
                            AnswerText = "Indonesia",
                            ExtraInfo = "273,523,615",
                            Points = 4,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c9809f7a-683f-4367-87cc-13fc5d891ee9"),
                            AnswerText = "Pakistan",
                            ExtraInfo = "220,892,340",
                            Points = 5,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a6fb5522-633a-4412-8176-6bd078f970fb"),
                            AnswerText = "Brazil",
                            ExtraInfo = "212,559,417",
                            Points = 6,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("9bd33f48-c741-42b1-b875-05b1e22f6be5"),
                            AnswerText = "Nigeria",
                            ExtraInfo = "206,139,589",
                            Points = 7,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("aff37bf4-3e74-45ae-bd9b-0587421adbff"),
                            AnswerText = "Bangladesh",
                            ExtraInfo = "164,689,383",
                            Points = 8,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5a3d609-0a3f-4c1b-9cdb-5b82428bf83d"),
                            AnswerText = "Russia",
                            ExtraInfo = "145,934,462",
                            Points = 9,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("d4711d9b-2267-4be5-9ea9-4e118a23285b"),
                            AnswerText = "Mexico",
                            ExtraInfo = "128,932,753",
                            Points = 10,
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b2710771-e4ff-4970-9246-fd87c35945d0"),
                            AnswerText = "Vatican",
                            ExtraInfo = "0.49 Km²",
                            Points = 1,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("26ad01ed-ff4e-488a-8075-f38e0a53dd1c"),
                            AnswerText = "Vatican City",
                            ExtraInfo = "0.49 Km²",
                            Points = 1,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("61713893-8f93-45f8-b460-5c3acabdf6cb"),
                            AnswerText = "Monaco",
                            ExtraInfo = "2.02 Km²",
                            Points = 2,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("dfe9aefb-c6a5-4fd6-a8c8-d44e6916af2e"),
                            AnswerText = "Nauru",
                            ExtraInfo = "21 Km²",
                            Points = 3,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("ab751480-bf1c-4a85-8cd6-4f05de1de83a"),
                            AnswerText = "Tuvalu",
                            ExtraInfo = "26 Km²",
                            Points = 4,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("9bc60ddc-d231-40f8-9095-75cb975d232e"),
                            AnswerText = "San Marino",
                            ExtraInfo = "61 Km²",
                            Points = 5,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("6242f756-a1cf-4675-b812-0c99b6b908a6"),
                            AnswerText = "Liechtenstein",
                            ExtraInfo = "160 Km²",
                            Points = 6,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("df6458dc-ef68-4746-8e7f-504af7b25fc4"),
                            AnswerText = "Marshall islands",
                            ExtraInfo = "181 Km²",
                            Points = 7,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("f6fe9038-a13e-484e-b654-57c7b3331293"),
                            AnswerText = "Saint kitts and nevis",
                            ExtraInfo = "261 Km²",
                            Points = 8,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("e1af8ab0-2db9-4ff4-874a-8ad066db06d2"),
                            AnswerText = "Saint kitts",
                            ExtraInfo = "261 Km²",
                            Points = 8,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("afecdbde-30f8-4011-bd6d-19ef67612489"),
                            AnswerText = "Saint nevis",
                            ExtraInfo = "261 Km²",
                            Points = 8,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("ee38b690-23e4-4e06-964a-fca36a361ec9"),
                            AnswerText = "kitts",
                            ExtraInfo = "261 Km²",
                            Points = 8,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("7e0ffcff-4654-4757-aef0-a7a30cfd0cda"),
                            AnswerText = "nevis",
                            ExtraInfo = "261 Km²",
                            Points = 8,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("db50c390-b73b-45ac-b51c-2e16075f8c30"),
                            AnswerText = "Maldives",
                            ExtraInfo = "300 Km²",
                            Points = 9,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        },
                        new
                        {
                            Id = new Guid("f43f0bf2-9c6b-4c46-903d-df0673156c43"),
                            AnswerText = "Malta",
                            ExtraInfo = "316 Km²",
                            Points = 10,
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        });
                });

            modelBuilder.Entity("QuizWebsite.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-100000000001"),
                            Name = "Countries"
                        });
                });

            modelBuilder.Entity("QuizWebsite.Core.Entities.CategoryQuestions", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("CategoryQuestions");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("00000000-0000-0000-0000-100000000001"),
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CategoryId = new Guid("00000000-0000-0000-0000-100000000001"),
                            QuestionId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            CategoryId = new Guid("00000000-0000-0000-0000-100000000001"),
                            QuestionId = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613")
                        });
                });

            modelBuilder.Entity("QuizWebsite.Core.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000000"),
                            QuestionText = "What are the biggest countries of the world"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000000"),
                            QuestionText = "What countries have the biggest population"
                        },
                        new
                        {
                            Id = new Guid("be90a71f-c2ee-4178-96c3-8adb2293b613"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000000"),
                            QuestionText = "What are the smallest countries of the world"
                        });
                });

            modelBuilder.Entity("QuizWebsite.Core.Entities.Answer", b =>
                {
                    b.HasOne("QuizWebsite.Core.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizWebsite.Core.Entities.CategoryQuestions", b =>
                {
                    b.HasOne("QuizWebsite.Core.Entities.Category", "Category")
                        .WithMany("CategoryQuestions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizWebsite.Core.Entities.Question", "Question")
                        .WithMany("CategoryQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
